name: Apply Spotless

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  spotlessApply:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    permissions:
      contents: write # For commiting formatted files

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-java
      - name: Apply spotless formatting
        run: ./gradlew --init-script gradle/init.gradle.kts --no-configuration-cache --continue spotlessApply
      - name: Apply spotless formatting (build-logic)
        run: ./gradlew --project-dir build-logic --init-script ../gradle/init.gradle.kts --no-configuration-cache --continue spotlessApply
      - name: Apply spotless formatting (app-template)
        run: ./gradlew --project-dir feature/app-builder/app-template --init-script ../../../gradle/init.gradle.kts --no-configuration-cache --continue spotlessApply
      - name: Auto-commit formatted files (non-fork PRs only)
        # Only auto-commit on pull requests from the same repository (not forks)
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ðŸ¤– Apply Spotless
